[package]
name = "stereo-matching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
rayon = "1.10.0"
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }